spring.application.name=FlyzyBot
spring.datasource.url=jdbc:mysql://localhost:3306/flyzydb
spring.datasource.username=root
spring.datasource.password=97532468cL@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
